name = "LocalPackages"
uuid = "8811483f-4b44-401a-9335-0b3c0b0b7028"
repo = "https://github.com/banhbio/LocalPackages.git"
description = "Julia Registry of banhbio"

[packages]
691e8c85-6b6e-4051-8c7e-8df901820a12 = { name = "GFF3Trees", path = "G/GFF3Trees" }
