name = "LocalPackages"
uuid = "8811483f-4b44-401a-9335-0b3c0b0b7028"
repo = "https://github.com/banhbio/LocalPackages.git"
description = "Julia Registry of banhbio"

[packages]
59c79803-3a52-40d7-aec0-3a5c885b2802 = { name = "BlastLCA", path = "B/BlastLCA" }
691e8c85-6b6e-4051-8c7e-8df901820a12 = { name = "GFF3Trees", path = "G/GFF3Trees" }
9684f9c8-20f2-452e-841c-c248fa1ab5f7 = { name = "RproteinFinder", path = "R/RproteinFinder" }
cfa2a8b1-67da-434d-80e9-378d2cda2752 = { name = "AbstractPhylo", path = "A/AbstractPhylo" }
