name = "LocalPackages"
uuid = "8811483f-4b44-401a-9335-0b3c0b0b7028"
repo = "https://github.com/banhbio/LocalPackages.git"
description = "Julia Registry of banhbio"

[packages]
5ae71ed2-6f8a-4ed1-b94f-e14e8158f19e = { name = "CombinedParsers", path = "C/CombinedParsers" }
666c268a-d78f-417b-b45a-09e10b365109 = { name = "Tries", path = "T/Tries" }
691e8c85-6b6e-4051-8c7e-8df901820a12 = { name = "GFF3Trees", path = "G/GFF3Trees" }
cfa2a8b1-67da-434d-80e9-378d2cda2752 = { name = "AbstractPhylo", path = "A/AbstractPhylo" }
